[colors]
foreground = "#ADB0BB"
background = "#1A1D23"
cursor_bg = "#ADB0BB"
cursor_border = "#ADB0BB"
cursor_fg = "#1A1D23"
selection_bg = "#26343F"
selection_fg = "#ADB0BB"
split = "#50A4E9"
compose_cursor = "#EB8332"
scrollbar_thumb = "#696C76"

ansi = ["#111317", "#FF838B", "#87C05F", "#DFAB25", "#5EB7FF", "#DD97F1", "#4AC2B8", "#9B9FA9"]
brights = ["#34363A", "#FFA6AE", "#AAE382", "#FFCE48", "#81DAFF", "#FFBAFF", "#6DE5DB", "#D0D3DE"]

[colors.tab_bar]
inactive_tab_edge = "#3A3E47"
background = "#1A1D23"

[colors.tab_bar.active_tab]
fg_color = "#ADB0BB"
bg_color = "#50A4E9"

[colors.tab_bar.inactive_tab]
fg_color = "#494D56"
bg_color = "#16181D"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#50A4E9"
bg_color = "#16181D"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#50A4E9"
bg_color = "#1A1D23"

[colors.tab_bar.new_tab]
fg_color = "#50A4E9"
bg_color = "#1A1D23"

[metadata]
aliases = []
author = "AstroNvim"
name = "astrodark"